### ISSUE TITLE
ImportError: cms blueprint appears to be broken.

### ISSUE THREAD

**Issue by FMJansen** [MPvHarmelen/Freevle#244]
So this
    $ python test.py ../settings.cfg
    Traceback (most recent call last):
      File "test.py", line 1, in <module>
        from freevle import testing
      File "/media/floris/08c99fbf-295f-43e5-8df7-709bf7e65d37/External/Werk/heroku-freevle/freevle/**init**.py", line 40, in <module>
        raise ImportError("{} blueprint appears to be broken.".format(bp_name))
    ImportError: cms blueprint appears to be broken.

**Comment by MPvHarmelen** [comment]
Meh, heroku doesn't moan =D
